# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
# Disable the blank line at the start of the prompt
add_newline = false

# Color palette from wallpaper
palette = "wallpaper"

[palettes.wallpaper]
sage_light = "#A8B8A8"
sage_mid = "#8B9A8B"
sage_dark = "#6B7B6B"
forest_green = "#4A5D4A"
forest_dark = "#3A4D3A"
slate_blue = "#707A8A"
muted_blue = "#5C6E7A"
warm_beige = "#B8AE9C"
text_primary = "#8B9A8B"
text_accent = "#7A8F7A"

[fill]
symbol = " "

[character]
success_symbol = '[➜](bold sage_light)'
error_symbol = '[➜](bold red)'

[directory]
style = "bold sage_mid"
read_only = " 󰌾"
read_only_style = "forest_dark"
truncation_length = 1
truncate_to_repo = false

[git_branch]
symbol = " "
style = "forest_green"

[git_status]
style = "muted_blue"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
staged = '[++\($count\)](sage_dark)'

[git_commit]
tag_symbol = '  '
style = "slate_blue"

[aws]
symbol = "  "
style = "muted_blue"

[buf]
symbol = " "
style = "sage_mid"

[c]
symbol = " "
style = "muted_blue"

[conda]
symbol = " "
style = "forest_green"

[crystal]
symbol = " "
style = "sage_light"

[dart]
symbol = " "
style = "slate_blue"

[docker_context]
symbol = " "
style = "muted_blue"

[elixir]
symbol = " "
style = "forest_green"

[elm]
symbol = " "
style = "sage_mid"

[fennel]
symbol = " "
style = "sage_dark"

[fossil_branch]
symbol = " "
style = "forest_green"

[golang]
symbol = " "
style = "muted_blue"

[guix_shell]
symbol = " "
style = "sage_mid"

[haskell]
symbol = " "
style = "forest_dark"

[haxe]
symbol = " "
style = "slate_blue"

[hg_branch]
symbol = " "
style = "forest_green"

[hostname]
ssh_symbol = " "
style = "sage_dark"

[java]
symbol = " "
style = "muted_blue"

[julia]
symbol = " "
style = "forest_green"

[kotlin]
symbol = " "
style = "slate_blue"

[lua]
symbol = " "
style = "sage_light"

[memory_usage]
symbol = "󰍛 "
style = "forest_dark"

[meson]
symbol = "󰔷 "
style = "sage_mid"

[nim]
symbol = "󰆥 "
style = "muted_blue"

[nix_shell]
symbol = " "
style = "sage_dark"

[nodejs]
symbol = " "
style = "forest_green"

[ocaml]
symbol = " "
style = "slate_blue"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[os]
style = "sage_mid"

[package]
symbol = "󰏗 "
style = "forest_dark"

[bun]
symbol = "🍔 "
style = "warm_beige"

[perl]
symbol = " "
style = "slate_blue"

[php]
symbol = " "
style = "muted_blue"

[pijul_channel]
symbol = " "
style = "forest_green"

[python]
symbol = " "
style = "sage_light"

[rlang]
symbol = "󰟔 "
style = "muted_blue"

[ruby]
symbol = " "
style = "forest_dark"

[rust]
symbol = "󱘗 "
style = "sage_dark"

[scala]
symbol = " "
style = "slate_blue"

[swift]
symbol = " "
style = "sage_mid"

[zig]
symbol = " "
style = "forest_green"

[gradle]
symbol = " "
style = "muted_blue"

[gcloud]
disabled = true

[username]
style_user = "sage_mid"
style_root = "forest_dark"

[time]
disabled = true
style = "sage_dark"
format = "[$time]($style) "

[cmd_duration]
style = "muted_blue"
